"""Added Spotify tokens

Revision ID: b3dd8cf55efd
Revises: 
Create Date: 2025-03-08 15:14:40.265671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3dd8cf55efd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_access_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('spotify_refresh_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('spotif_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('spotif_token_expiry')
        batch_op.drop_column('spotify_refresh_token')
        batch_op.drop_column('spotify_access_token')

    # ### end Alembic commands ###
